### ISSUE TITLE
CRC params incorrect? or alternate params used for some games?

### ISSUE THREAD

**Issue by cgarz** [Andys-Dreamcast-Projects/makeip#2]
When comparing the header CRC of various game headers on Redump to the output of makeip, the results sometimes do not match what is written in the game header.

For example:
|     Input Data     |  makeip CRC  | Game Header's Data | Redump Link |
| :----------------: | :----------: | :----------------: | :---------: |
| `T6802M    V1.003` |     787E     | `7CDD GD-ROM1/1  ` | [/disc/5845/](http://redump.org/disc/5845/) |
| `610716402 V1.001` |     37AB     | `E258 GD-ROM1/1  ` | [/disc/41330/](http://redump.org/disc/41330/) |
| `HDR-0023  V1.002` |     3AEB     | `67E0 GD-ROM1/1  ` | [/disc/18631/](http://redump.org/disc/18631/) |
| `T7002D 50 V1.000` |     6ECB     | `95B1 GD-ROM1/1  ` | [/disc/10676/](http://redump.org/disc/10676/) |

Most of the time it does seem to work though:
|     Input Data     |  makeip CRC  | Game Header's Data | Redump Link |
| :----------------: | :----------: | :----------------: | :---------: |
| `T36813D 05V1.000` |     EE38     | `EE38 GD-ROM1/1  ` | [/disc/69034/](http://redump.org/disc/69034/) |
| `T8114D  50V1.004` |     1F56     | `1F56 GD-ROM1/1  ` | [/disc/18108/](http://redump.org/disc/18108/) |
| `T1235M    V1.003` |     DAAE     | `DAAE GD-ROM1/1  ` | [/disc/42518/](http://redump.org/disc/42518/) |
| `T65181N   V1.000` |     472B     | `472B CD-ROM1/1  ` | [/disc/70319/](http://redump.org/disc/70319/) |

Could the params be wrong? Though, I'm not sure if it would even be possible to have different CRC params that would make it only sometimes not match. CRC is like black magic to me :laughing:

Or is there perhaps alternate params used for certain games?

**Comment by andressbarajas** [comment]
Honestly, idk. I was using the crc algorithm that was floating around.  I should have archived this repo because it has been redone and exists in the KOS repo here: https://github.com/Dreamcast-Projects/KallistiOS/tree/master/utils/makeip
